### ISSUE TITLE
Not working with UE5.2

### ISSUE THREAD

**Issue by jahidhasanlinix** [tomlooman/ActionRoguelike#11]
I downloaded the whole new project from branch 5.1, I have UE5.2 installed but when I tried to open it in Visual Studio 2022, it's not working for me. I can not start the project due to this issue. I really need help to fix it so I can start the course. Thank you

**Comment by tomlooman** [comment]
You can use the 'master' branch rather than picking the 5.1 version. The master is upgraded to 5.2
