### ISSUE TITLE
where are the course video lectures?

### ISSUE THREAD

**Issue by universewill** [tomlooman/ActionRoguelike#2]
I visited https://www.tomlooman.com/stanford-cs193u/, but I can not find the video courses.

**Comment by tomlooman** [comment]
That was the course page for the live classes. The recordings are still being edited and are not yet online right now. Once they are, check YouTube and my site where they will be posted.

**Comment by varomix** [comment]
Looking forward to this video lessons, thanks for sharing

**Comment by salimp2009** [comment]
count me in...even a new class on UEs Gameplay in c++ and some  and BP for the rest would be awesome TOO :)

**Comment by salimp2009** [comment]
what is the UE4.25 branch . Is this the blank project ? start of the project or just 4.25 version of the finished project

**Comment by tomlooman** [comment]
None of the branches are a 'clean' project, it's just the associated version of the finished project. 

For the lectures, students will create an empty project within unreal engine directly.

**Comment by salimp2009** [comment]
thnk you Tom....I will wait for the videos and create my version based on those. I might even start trying on the assignments maybe that are on the class web page but i dont have much experience on Multiplayer; get confused sometimes where to use Muticast or RepNotify and what has to be replicated and what not.  i also have also your Udemy  class which i will start soon once i finish some other classes. Already learned a little on both the Unreal Ability System and also learning some Multiplayer on BP ; Next one i want to use both C++ and BP with as efficient I can; using Interfaces; 
your classes and Unreal ActionRPG will good resources for that. Thank you for doing all this .

**Comment by farhatabbas1998** [comment]
Hi can i have your youtube link? thanks
