### ISSUE TITLE
Update IsPendingKill to IsValid

### ISSUE THREAD

**Issue by namrog84** [tomlooman/ActionRoguelike#5]
Deprecation: "IsPendingKill() should no longer be used. Use IsValid(Object), IsValidChecked(Object) or GetValid(Object) instead."

While it's not yet deprecated in UE 4.27(it is in 5.0), I thought IsValid is a valid replacement at that point and should still accomplish the same goal.

https://github.com/tomlooman/ActionRoguelike/blob/master/Source/ActionRoguelike/Private/SProjectileBase.cpp#L51
https://github.com/tomlooman/ActionRoguelike/blob/master/Source/ActionRoguelike/Private/SSaveGameSubsystem.cpp#L43
https://github.com/tomlooman/ActionRoguelike/blob/master/Source/ActionRoguelike/Private/SSaveGameSubsystem.cpp#L117

I am not sure if you accept PRs, but these should probably be updated at some point.

**Comment by tomlooman** [comment]
Thanks! I've noted this down for once 5.0 is released. I'll refresh the repository afterward and will have to include this change into the course as well.
